### ISSUE TITLE
Defining Milestones

### ISSUE THREAD

**Issue by ffguven** [bounswe/bounswe2017group9#38]
A Google sheet is created and milestone assignment is divided to group members. All group members will add their own milestone description to Google sheet.

Work sharing is like that :

- [x]  Milestone 1 -> @aticie and @kahremane 
- [x]  Milestone 2 -> @necipfazilergun and @mehmetakify 
- [x]  Milestone 3 -> @begununal and @hilaldonmez 
- [x]  Milestone 4 -> @ozturkihsan and @dogacandorum 
- [x]  Milestone 5 -> @ffguven
- [x]  Milestone 6 -> @aticie and @kahremane 
- [x]  Milestone 7 -> @kasimbozdag 

After finishing to edit Google sheet, everyone will draw gantt chart for his/her own milestone and the final work will be added to Wiki.

**Comment by aticie** [comment]
I think we can close this issue for now. We can reopen it when it needs a revision.
